# Generated by Django 4.2.5 on 2023-10-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_formtransition_form_userform_transitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtransition',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='formtransition',
            name='sender_user',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='transitions',
        ),
        migrations.AddField(
            model_name='formtransition',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formtransition',
            name='receivers_role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Chief Officer', 'Chief Officer'), ('CEO Deligate', 'CEO Deligate'), ('CFO', 'CFO'), ('Accountant', 'Accountant'), ('Business Development Manager', 'Business Development Manager'), ('Business Development Specialist', 'Business Development Specialist'), ('Marketing Moderator', 'Marketing Moderator'), ('Marketing Specialist', 'Marketing Specialist'), ('IT Specialist', 'IT Specialist'), ('Technical Moderator', 'Technical Moderator'), ('Subline Chain Technation(Logistic)', 'Subline Chain Technation(Logistic)'), ('Factory', 'Factory'), ('QC Technation', 'QC Technation')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Chief Officer', 'Chief Officer'), ('CEO Deligate', 'CEO Deligate'), ('CFO', 'CFO'), ('Accountant', 'Accountant'), ('Business Development Manager', 'Business Development Manager'), ('Business Development Specialist', 'Business Development Specialist'), ('Marketing Moderator', 'Marketing Moderator'), ('Marketing Specialist', 'Marketing Specialist'), ('IT Specialist', 'IT Specialist'), ('Technical Moderator', 'Technical Moderator'), ('Subline Chain Technation(Logistic)', 'Subline Chain Technation(Logistic)'), ('Factory', 'Factory'), ('QC Technation', 'QC Technation')], max_length=45),
        ),
        migrations.AlterField(
            model_name='userform',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
