# Generated by Django 4.2.5 on 2023-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_form_id_userform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
