# Generated by Django 4.2.5 on 2023-11-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_userform_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtransition',
            name='receiver_user',
        ),
        migrations.AddField(
            model_name='formtransition',
            name='next_transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.formtransition'),
        ),
    ]
