# Generated by Django 4.2.5 on 2023-11-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_formtransition_receiver_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtransition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='transitions',
        ),
        migrations.AddField(
            model_name='formsample',
            name='transitions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='current_transition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.formtransition'),
        ),
        migrations.AlterField(
            model_name='formtransition',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
