# Generated by Django 4.2.5 on 2023-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_formtransition_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='current_receiver',
        ),
        migrations.AddField(
            model_name='userform',
            name='all_transitions',
            field=models.ManyToManyField(related_name='all_transitions', to='dashboard.formtransition'),
        ),
    ]
