# Generated by Django 4.2.5 on 2023-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_userform_current_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtransition',
            name='status',
            field=models.CharField(choices=[('og', 'On Going'), ('ac', 'Accepted'), ('dc', 'Declined')], default='og', max_length=150),
        ),
    ]
