# Generated by Django 4.2.5 on 2023-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_formtransition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtransition',
            name='status',
            field=models.CharField(choices=[('edit', 'Must Be Edited'), ('sb', 'Sent Back'), ('ac', 'Accepted'), ('dc', 'Declined')], default='og', max_length=150),
        ),
    ]
