# Generated by Django 4.2.5 on 2023-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_formtransition_prev_transition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtransition',
            name='sign',
            field=models.FileField(null=True, upload_to='uploads/signs/'),
        ),
    ]
