# Generated by Django 4.2.5 on 2023-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_formtransition_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtransition',
            name='sign',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
