# Generated by Django 4.2.5 on 2023-11-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_formtransition_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtransition',
            name='receivers_role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Chief Officer', 'Chief Officer'), ('CEO Deligate', 'CEO Deligate'), ('CFO', 'CFO'), ('Accountant', 'Accountant'), ('Business Development Manager', 'Business Development Manager'), ('Business Development Expert', 'Business Development Expert'), ('Marketing Moderator', 'Marketing Moderator'), ('Marketing Expert', 'Marketing Expert'), ('IT Expert', 'IT Expert'), ('Technical Moderator', 'Technical Moderator'), ('Logistic Expert', 'Logistic Expert'), ('Factory', 'Factory'), ('QC Expert', 'QC Expert')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Chief Officer', 'Chief Officer'), ('CEO Deligate', 'CEO Deligate'), ('CFO', 'CFO'), ('Accountant', 'Accountant'), ('Business Development Manager', 'Business Development Manager'), ('Business Development Expert', 'Business Development Expert'), ('Marketing Moderator', 'Marketing Moderator'), ('Marketing Expert', 'Marketing Expert'), ('IT Expert', 'IT Expert'), ('Technical Moderator', 'Technical Moderator'), ('Logistic Expert', 'Logistic Expert'), ('Factory', 'Factory'), ('QC Expert', 'QC Expert')], max_length=45),
        ),
        migrations.AlterField(
            model_name='userform',
            name='status',
            field=models.CharField(choices=[('og', 'On Going'), ('sb', 'Submitted'), ('dc', 'Declined')], max_length=50),
        ),
    ]
