# Generated by Django 4.2.5 on 2023-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_formtransition_receivers_role_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='status',
            field=models.CharField(choices=[('og', 'On Going'), ('sb', 'Submitted'), ('dc', 'Declined')], default='og', max_length=50),
        ),
    ]
