# Generated by Django 4.2.5 on 2023-11-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_userform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='status',
            field=models.CharField(choices=[('og', 'On Going'), ('edit', 'Must Be Edited'), ('sm', 'Submitted'), ('dc', 'Declined')], default='og', max_length=50),
        ),
    ]
