# Generated by Django 4.2.5 on 2023-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_formtransition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='descrition',
        ),
        migrations.AlterField(
            model_name='userform',
            name='status',
            field=models.CharField(blank=True, choices=[('og', 'On Going'), ('edit', 'Must Be Edited'), ('sm', 'Submitted'), ('dc', 'Declined')], max_length=50, null=True),
        ),
    ]
