# Generated by Django 4.2.5 on 2023-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0004_alter_dailytasks_goal_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='topic',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlytasks',
            name='goal',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
