# Generated by Django 4.2.5 on 2023-09-27 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0005_alter_dailytasks_topic_alter_monthlytasks_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlytasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
