# Generated by Django 4.2.5 on 2023-09-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0006_dailytasks_created_at_monthlytasks_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytasks',
            name='description',
        ),
    ]
