# Generated by Django 4.2.5 on 2023-09-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0007_remove_dailytasks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='actual_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dailytasks',
            name='status',
            field=models.CharField(choices=[('jc', 'Just Created'), ('cba', 'Checked By Admin'), ('edt', 'Edited'), ('done', 'Done'), ('nd', 'Not Done')], default='og', max_length=150),
        ),
    ]
