# Generated by Django 4.2.5 on 2023-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0008_dailytasks_actual_time_dailytasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytasks',
            name='status',
            field=models.CharField(choices=[('og', 'On Going'), ('done', 'Done'), ('nd', 'Not Done')], default='og', max_length=150),
        ),
        migrations.AlterField(
            model_name='dailytasks',
            name='status',
            field=models.CharField(choices=[('jc', 'Just Created'), ('cba', 'Checked By Admin'), ('edt', 'Edited'), ('done', 'Done'), ('nd', 'Not Done')], default='jc', max_length=150),
        ),
    ]
