# Generated by Django 4.2.5 on 2023-10-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0010_alter_dailytasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytasks',
            name='admin_comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='monthlytasks',
            name='goal',
            field=models.CharField(max_length=150),
        ),
    ]
