# Generated by Django 4.2.5 on 2023-10-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0012_dailytasks_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='topic',
            field=models.CharField(max_length=150),
        ),
    ]
