# Generated by Django 4.2.5 on 2023-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0013_alter_dailytasks_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='checked_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailytasks',
            name='status',
            field=models.CharField(choices=[('jc', 'Just Created'), ('og', 'On Going'), ('edt', 'Edited'), ('done', 'Done'), ('nd', 'Not Done')], default='jc', max_length=150),
        ),
    ]
