# Generated by Django 4.2.5 on 2023-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0014_dailytasks_checked_by_admin_alter_dailytasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='checked_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
