# Generated by Django 4.2.5 on 2023-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0017_monthlytasks_checked_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytasks',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
