# Generated by Django 4.2.5 on 2023-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0018_monthlytasks_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytasks',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
