# Generated by Django 4.2.5 on 2023-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0019_dailytasks_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
