# Generated by Django 4.2.5 on 2023-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCT', '0020_alter_dailytasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
