# Generated by Django 4.2.5 on 2023-09-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230920_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsample',
            old_name='descrition',
            new_name='description',
        ),
    ]
