# Generated by Django 4.2.5 on 2023-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestionsample_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionsample',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
    ]
